name       : tessdata
version    : 3.04.00
release    : 1
source     :
    - https://github.com/tesseract-ocr/tessdata/archive/3.04.00.tar.gz : 5dcb37198336b6953843b461ee535df1401b41008d550fc9e43d0edabca7adb1
license    : Apache-2.0
component  : office
summary    : This repository contains language data for Tesseract Open Source OCR Engine.
description: |
    This repository contains language data for Tesseract Open Source OCR Engine.
install    : |
    install -d $installdir/usr/share/tessdata
    cp ./* $installdir/usr/share/tessdata/
    chmod 00644 $installdir/usr/share/tessdata/*
