name       : tessdata
version    : 4.1.0
release    : 3
source     :
    - https://github.com/tesseract-ocr/tessdata/archive/refs/tags/4.1.0.tar.gz : 990fffb9b7a9b52dc9a2d053a9ef6852ca2b72bd8dfb22988b0b990a700fd3c7
homepage   : https://github.com/tesseract-ocr/tessdata
license    : Apache-2.0
component  : office
summary    : Trained models with support for legacy and LSTM OCR engine
description: |
    This repository contains language data for Tesseract Open Source OCR Engine.
install    : |
    install -dm00644 $installdir/usr/share/tessdata
    install -Dm00644 *.traineddata $installdir/usr/share/tessdata
